print("verified by me!!!!!!!!!!!!!!!!!!")
print("Who")
print("me!!!!!!!!!!!!!!!!!!")
print("Whoo???")
print("yahh meee!!")
print("OH u again???")
print("yah me again!")
print("whyyy??")
print("what why")
print("hmmm....")
print("Nothing!")