print("verified by me!!!!!!!!!!!!!!!!!!")
print("Who")
print("me!!!!!!!!!!!!!!!!!!")
print("Whoo???")
print("yahh meee!!")
print("OH u again???")
print("yah me again!")
print("whyyyuuuuuuuuuuuuuuuuuuu??")
print("what wuuuuuuhy")
print("hmmm....")
print("Nothing mamma!!")